# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
 #use_frameworks!

  # Pods for Demo
pod 'ReactiveCocoa’,'~> 2.1.8'
pod 'Masonry'
end
